"""initial_schema

Revision ID: ee5ab1c73b8e
Revises: 
Create Date: 2026-09-17 23:06:01.501422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'ee5ab1c73b8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure PostGIS extension is available
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('reservoir', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('farmers_contacted', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_log_triggered_at'), 'alert_log', ['triggered_at'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=True)
    op.create_table('dam_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservoir', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('full_depth_ft', sa.Float(), nullable=True),
    sa.Column('full_capacity_mcft', sa.Float(), nullable=True),
    sa.Column('current_level_ft', sa.Float(), nullable=True),
    sa.Column('current_storage_mcft', sa.Float(), nullable=True),
    sa.Column('current_inflow_cusecs', sa.Float(), nullable=True),
    sa.Column('current_outflow_cusecs', sa.Float(), nullable=True),
    sa.Column('last_year_level_ft', sa.Float(), nullable=True),
    sa.Column('last_year_storage_mcft', sa.Float(), nullable=True),
    sa.Column('storage_percentage', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservoir', 'date', name='uq_dam_reservoir_date')
    )
    op.create_index('ix_dam_date', 'dam_status', ['date'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('primary_crop', sa.String(length=100), nullable=True),
    sa.Column('sowing_date', sa.DateTime(), nullable=True),
    sa.Column('days_after_sowing', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('last_called', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: GeoAlchemy2 auto-creates spatial index 'idx_farmers_geom' for geography columns
    op.create_index(op.f('ix_farmers_district'), 'farmers', ['district'], unique=False)
    op.create_index(op.f('ix_farmers_phone'), 'farmers', ['phone'], unique=True)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=200), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('normalized_term', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=200), nullable=True),
    sa.Column('transcript_ref', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_proposed_meaning', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_call_id'), 'flags', ['call_id'], unique=False)
    op.create_index(op.f('ix_flags_district'), 'flags', ['district'], unique=False)
    op.create_index(op.f('ix_flags_normalized_term'), 'flags', ['normalized_term'], unique=False)
    op.create_index(op.f('ix_flags_status'), 'flags', ['status'], unique=False)
    op.create_table('regional_dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('standard_meaning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_confirmed_confidence', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district', 'term', name='uq_regional_dict_district_term')
    )
    op.create_table('system_meta',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('weather_cache',
    sa.Column('cache_key', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('call_transcript_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_db_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_ref', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_db_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_transcript_turns_call_db_id'), 'call_transcript_turns', ['call_db_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_farmer_id'), 'conversation_turns', ['farmer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_turns_farmer_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_call_transcript_turns_call_db_id'), table_name='call_transcript_turns')
    op.drop_table('call_transcript_turns')
    op.drop_table('weather_cache')
    op.drop_table('system_meta')
    op.drop_table('regional_dictionary')
    op.drop_index(op.f('ix_flags_status'), table_name='flags')
    op.drop_index(op.f('ix_flags_normalized_term'), table_name='flags')
    op.drop_index(op.f('ix_flags_district'), table_name='flags')
    op.drop_index(op.f('ix_flags_call_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_farmers_phone'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_district'), table_name='farmers')
    # Note: idx_farmers_geom is auto-managed by GeoAlchemy2
    op.drop_table('farmers')
    op.drop_index('ix_dam_date', table_name='dam_status')
    op.drop_table('dam_status')
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_alert_log_triggered_at'), table_name='alert_log')
    op.drop_table('alert_log')
    # ### end Alembic commands ###
